on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - run: |-
        gcloud auth configure-docker
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - uses: buildpacks/github-actions/setup-pack@v4.1.0

    - run: |-
        pack build --builder=gcr.io/buildpacks/builder:v1 --publish \
          gcr.io/$PROJECT_ID/cloudbowl-samples-python:$GITHUB_SHA

#    - run: |-
#        kubectl apply -f deployment.yml
#        kubectl rollout status deployment/$DEPLOYMENT_NAME
#        kubectl get services -o wide
